// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// productController is an autogenerated mock type for the productController type
type productController struct {
	mock.Mock
}

type mockConstructorTestingTnewProductController interface {
	mock.TestingT
	Cleanup(func())
}

// newProductController creates a new instance of productController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newProductController(t mockConstructorTestingTnewProductController) *productController {
	mock := &productController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
