// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// transactionController is an autogenerated mock type for the transactionController type
type transactionController struct {
	mock.Mock
}

type mockConstructorTestingTnewTransactionController interface {
	mock.TestingT
	Cleanup(func())
}

// newTransactionController creates a new instance of transactionController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newTransactionController(t mockConstructorTestingTnewTransactionController) *transactionController {
	mock := &transactionController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
