-- PostgreSQL for ERD Generated

CREATE TABLE Users (
    ID INTEGER PRIMARY KEY,
    CreatedAt TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP NOT NULL,
    Username VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Points INTEGER NOT NULL
);

CREATE TABLE Products (
    ID INTEGER PRIMARY KEY,
    CreatedAt TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP NOT NULL,
    Category VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    Description VARCHAR(255) NOT NULL,
    Price INTEGER NOT NULL,
    Stock INTEGER NOT NULL,
    Image VARCHAR(255) NOT NULL,
    CreatedBy VARCHAR(255) NOT NULL,
    UpdatedBy VARCHAR(255) NOT NULL,
    FOREIGN KEY (CreatedBy) REFERENCES Admins(Name),
    FOREIGN KEY (UpdatedBy) REFERENCES Admins(Name)
);

CREATE TABLE SerialNumbers (
    ID INTEGER PRIMARY KEY,
    CreatedAt TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP NOT NULL,
    SerialNumber VARCHAR(255) NOT NULL,
    ProductID INTEGER NOT NULL,
    Status VARCHAR(255) NOT NULL,
    CreatedBy VARCHAR(255) NOT NULL,
    FOREIGN KEY (ProductID) REFERENCES Products(ID),
    FOREIGN KEY (CreatedBy) REFERENCES Admins(Name)
);

CREATE TABLE Transactions (
    ID INTEGER PRIMARY KEY,
    CreatedAt TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP NOT NULL,
    UserID INTEGER NOT NULL,
    ProductID INTEGER NOT NULL,
    SerialNumber VARCHAR(255) NOT NULL,
    IdentifierNum VARCHAR(255) NOT NULL,
    TotalPrice INTEGER NOT NULL,
    Status VARCHAR(255) NOT NULL,
    LastUpdatedBy VARCHAR(255) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(ID),
    FOREIGN KEY (ProductID) REFERENCES Products(ID),
    FOREIGN KEY (LastUpdatedBy) REFERENCES Admins(Name)
);

CREATE TABLE Admins (
    ID INTEGER PRIMARY KEY,
    CreatedAt TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP NOT NULL,
    Name VARCHAR(255) NOT NULL,
    Username VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL
);