-- PostgreSQL for ERD Generated

CREATE TABLE Users (
    ID VARCHAR(255) PRIMARY KEY,
    CreatedAt TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP NOT NULL,
    Role VARCHAR(255) NOT NULL,
    Username VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE Points (
    ID VARCHAR(255) PRIMARY KEY,
    UserID VARCHAR(255) NOT NULL,
    Points INT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(ID)
);

CREATE TABLE Products (
    ID VARCHAR(255) PRIMARY KEY,
    CreatedAt TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP NOT NULL,
    Category VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    Description VARCHAR(255) NOT NULL,
    Price INTEGER NOT NULL,
    Stock INTEGER NOT NULL,
    Image VARCHAR(255) NOT NULL
);

CREATE TABLE SerialNumbers (
    ID VARCHAR(255) PRIMARY KEY,
    CreatedAt TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP NOT NULL,
    SerialNumber VARCHAR(255) NOT NULL,
    ProductID INTEGER NOT NULL,
    Status VARCHAR(255) NOT NULL,
    FOREIGN KEY (ProductID) REFERENCES Products(ID)
);

CREATE TABLE Transactions (
    ID INTEGER PRIMARY KEY,
    CreatedAt TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP NOT NULL,
    UserID INTEGER NOT NULL,
    ProductID INTEGER NOT NULL,
    SerialNumber VARCHAR(255) NOT NULL,
    IdentifierNum VARCHAR(255) NOT NULL,
    Price INTEGER NOT NULL,
    Status VARCHAR(255) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(ID),
    FOREIGN KEY (ProductID) REFERENCES Products(ID)
);